CREATE DATABASE app;
GRANT ALL PRIVILEGES ON app.* TO guest@localhost IDENTIFIED BY 'guest';
FLUSH PRIVILEGES;
use app;

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    email VARCHAR(32) NOT NULL,
    PRIMARY KEY (id)
);