spring:
  application:
    name: Message API
  datasource:
    tomcat:
      test-on-borrow: true
      validation-interval: 30000
      validation-query: SELECT 1
      remove-abandoned: true
      remove-abandoned-timeout: 10000
      log-abandoned: true
      log-validation-errors: true
      max-age: 1800000
      max-active: 50
      max-idle: 10
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    #    driverClassName: com.mysql.jdbc.Driver
    #    url: "jdbc:mysql://localhost:3306/app?autoReconnect=true&useSSL=false"
    username: guest
    password: guest
  flyway:
    url: jdbc:h2:mem:app # http://localhost:8080/h2-console
    #    url: jdbc:mysql://localhost:3306/app?useSSL=false
    user: "guest"
    password: "guest"
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: Initial
    locations: classpath:/db/migration
  h2:
    console:
      enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin # Default is /actuator
