spring:
  application:
    name: Message API
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/app?autoReconnect=true&useSSL=false"
    username: "guest"
    password: "guest"
  flyway:
    url: jdbc:mysql://localhost:3306/app?useSSL=false
    user: "guest"
    password: "guest"
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: Initial
    locations: classpath:/db/migration
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin # Default is /actuator
