version: "3.7"
services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: shinyay/mysql:5.7
    container_name: my_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
      MYSQL_DATABASE: guest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./log/mysql:/var/log/mysql
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_admin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "1111:80"