CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    mail_address VARCHAR(255),
    password CHAR(30),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);